version: '3'
services:
  db:
    image: mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: vpiusr
      MYSQL_PASSWORD: accesskey
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    restart:
      on-failure

volumes:
  db_data:

networks:
  backend: 
